algoritmo "horas de trabalho"
// Função :
// Autor :
// Data : 29/11/2021
// Seção de Declarações
var
salario_Mensal: inteiro
horas_Trabalhadas: inteiro
valor_Hora: real
inicio
escreval ("Qual é o seu salário mensal?")
leia (salario_Mensal)
escreval ("Quantas horas você trabalha por mês?")
leia (horas_Trabalhadas)
valor_Hora <-(salario_Mensal / horas_Trabalhadas)
escreval ("O Valor da sua hora é de R$", valor_Hora)
fimalgoritmo
